Wanted:
  # Use wanted.receive.(number) to change player wanted number
  Maximum: 5
  # Refresh interval of the compass, Recommended to keep this 10-20. In ticks (20 Ticks = 1 second)
  CompassRefreshInterval: 20
  StopFindingAfterDeath: true
  RemoveWantedOnlyIfKilledByHunter: false
  # In the arrest mode there is no need to kill Wanted player.
  # The Hunters/Police can use /wanted arrest <player> command to arrest Wanted player
  ArrestMode:
    # Should arrest mode be enabled?
    Enable: false
    # Prevent to player arrest himself
    PreventSelfArrest: true
    # The minimum distance between Player and the target to arrest
    Distance: 10
  # !!! ** Only supports WorldGuard 7.X ** !!!
  # !!! ** Only supports WorldGuard 7.X ** !!!
  # !!! ** Only supports WorldGuard 7.X ** !!!
  # Use this feature to blacklist/whitelist regions in server
  WorldGuard:
    # Should WorldGuard RegionFilter be enabled
    Enable: false
    # Revert the blacklist regions to whitelist regions
    RevertBlacklist: false
    # The list of blacklisted regions
    BlacklistRegions:
      - example1
  # ComplaintMode is a feature that prevents the killer wanted receive and allow victims to complain killers
  # Conditions:
  # - The victim should have wanted.complaint permission
  # - The killer should not be op or have access to wanted.bypass
  # - ComplaintMode should be enabled on the config file.
  ComplaintMode:
    # Should complaint mode be enabled?
    Enable: false
    ExpireTime: 15
  TrackerBossBar:
    Enable: true
    RefreshInterval: 20
    Default:
      Color: "GREEN"
      Type: "SOLID"
    Custom:
      # Custom BossBars should sort by the smallest distance.
      1:
        Distance: 50
        Progress: true
        Color: "RED"
        Type: "SOLID"
      2:
        Distance: 100
        Progress: true
        Color: "YELLOW"
        Type: "SOLID"
  LanguageFile: en_US
  ClearWantedOnDeath: true
  ReceiveOnKill:
    # You can use "wanted.receive.X" permission node to decide how many Wanted(s) should a player get when they kill someone,
    #  This is the default value, If someone didn't have that permission, this value will be used.
    Player:
      Enable: true
      KillMessage: true
      # Prevent Wanted receive if the killer is not the fight starter.
      PreventReceiveIfDefender: false
      Receive: 1
      RunCommandOnKill:
        Enable: false
        Commands:
          - 'KILLER;spawn'
          - 'VICTIM;spawn'
          - 'CONSOLE;say %victim% died'
          - 'CONSOLE;say %killer% killed %victim%'
    NPC:
      Enable: true
      KillMessage: true
      Receive: 2
      RunCommandOnKill:
        Enable: false
        Commands:
          - 'KILLER;spawn'
          - 'CONSOLE;say %victim% died'
          - 'CONSOLE;say %killer% killed %victim%'
    Mob:
      Enable: false
      KillMessage: true
      RunCommandOnKill:
        Enable: false
        Commands:
          - 'KILLER;spawn'
          - 'CONSOLE;say %victim% died'
          - 'CONSOLE;say %killer% killed %victim%'
      # You can use "ENTITY;WANTED" to decide how many Wanted(s) should a player get when they kill specific mobs.
      Mobs:
        - COW;1
        - CHICKEN;1
        - PIG;2
        - ZOMBIE;-1
        - CREEPER;-2
    Wanted:
      RunCommandOnKill:
        Enable: false
        # If the Wanted killer has wanted.hunter permission the below commands will run.
        Commands:
          - 'CONSOLE;give %killer% diamond %wanted_level%'