Wanted:
  # use wanted.receive.(number) to change player wanted number
  Maximum: 5
  # You can use "wanted.receive.X" permission node to decide how many wanteds should a player get when they kill someone,
  #  This is the default value, If someone didn't have that permission, this value will be used.
  ReceiveOnKill: 1
  # Refresh interval of the compass, Recommended to keep this 10-20. In ticks (20 Ticks = 1 second)
  CompassRefreshInterval: 20

# Data save interval in minute.
DataSave:
  Enable: true
  Interval: 30