Wanted:
  # use wanted.receive.(number) to change player wanted number
  Maximum: 5
  # Refresh interval of the compass, Recommended to keep this 10-20. In ticks (20 Ticks = 1 second)
  CompassRefreshInterval: 20
  LanguageFile: en_US
  ClearWantedOnDeath: true
  ReceiveOnKill:
    # You can use "wanted.receive.X" permission node to decide how many Wanted(s) should a player get when they kill someone,
    #  This is the default value, If someone didn't have that permission, this value will be used.
    Player:
      Enable: true
      KillMessage: true
      Receive: 1
    NPC:
      Enable: true
      KillMessage: true
      Receive: 2
    Mob:
      Enable: false
      KillMessage: true
      # You can use "ENTITY;WANTED" to decide how many Wanted(s) should a player get when they kill specific mobs.
      Mobs:
        - COW;1
        - CHICKEN;1
        - PIG;2
        - ZOMBIE;-1
        - CREEPER;-2